# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)

variables:
  solution: '**/SimpleMauiMVVM.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '$(solution)'
      versioningScheme: 'byBuildNumber'
